### ISSUE TITLE
Grid reporting incorrect values

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#1193]
**Description**

Grid reporting wrong values for bid and ask columns under "Default" formatting. Discovered in latest Silverheels release, requires high priority hotfix. Should require a regression test as part the fix so that this can never re-occur.

**Steps to reproduce**
[reproducer.csv](https://github.com/deephaven/web-client-ui/files/11139371/reproducer.csv)

1. import the sample csv attached about into the console to import it.
2. View the Bid and Ask columns.

**Expected results**
First bid should be `33.01`

**Actual results**

Bid and ask report as `0.00` for all values. Changing formatting on the specific column to anything other than default works correctly.

**Versions**

Engine Version: 0.23.0
Web UI Version: 0.32.0
Java Version: 17.0.6
Barrage Version: 0.5.0

**Comment by mofojed** [comment]
Cannot reproduce in Community, can only seem to reproduce in Enterprise... 
Tested on Enterprise ` 1.20230131.113 `,
Community:
```
Engine Version: 0.23.0
Web UI Version: 0.34.0
Java Version: 11.0.15
Barrage Version: 0.5.0
```

**Comment by dsmmcken** [comment]
Noting that default formatting rules are set for those columns in the workspace:
![image](https://user-images.githubusercontent.com/1576283/229550944-1b549caf-03cc-4210-8522-fb79bbde60d7.png)

**Comment by mofojed** [comment]
Bug was first introduced with https://github.com/deephaven/web-client-ui/commit/e0d6f07bcc9aeebab96cc25589081099aa935413#diff-49746d2c30b9fcf750915ac41f05b03d6cb79e6b783d276a7715134e5a567d75
We changed the check from:
```
const value =
      format && format.multiplier ? valueParam * format.multiplier : valueParam;
```
To:
```
      format && format.multiplier !== undefined && format.multiplier !== 0
        ? valueParam * format.multiplier
        : valueParam;
```
Which _would_ have been correct if the typing for `multiplier` had been correctly set to `multiplier?: number | null` to handle cases where multiplier was set to `null` in existing Enterprise default settings. However, that was incorrectly typed when this change was made: https://github.com/deephaven/web-client-ui/commit/922d4442f2080af3fda339ca9cae7b54b84d9821#diff-a8c4e784e5f1a95ab9987ada21900f63f3a02cde1aa56bf6d35f2a68ade811ef
Which was actually labelled as a BREAKING CHANGE, but didn't mention `multiplier` now only accepted `undefined` instead of `undefined` or `null`.

To fix this, I'm just going to allow `multiplier` to be `undefined | null`, rather than require workspace data migration.

**Comment by dsmmcken** [comment]
So Silverheels and forward for enterprise. Good investigation.
