### ISSUE TITLE
Add JS plugin information to Settings/Version information

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#1374]
As a user, I want some way in the UI that I can see what plugins are loaded so that I can verify what version of a plugin is loaded easily.

**Comment by mofojed** [comment]
This would be a good one for Akshat. @mattrunyon may have some guidance as well.

**Comment by mofojed** [comment]
As discussed on our huddle:
- Plugin version information is only available in the manifest.json
- We should add it to the `PluginModuleMap` so that it is available when calling `usePlugins`, e.g. something like:
```
export type VersionedPluginModule = PluginModule & { version: string };

export type PluginModuleMap = Map<string, VersionedPluginModule>;
```
- Add the version to the `PluginModuleMap` when loading plugins (in `PluginsBootstrap#loadModulePlugins`)

**Comment by AkshatJawne** [comment]
@mofojed Been working on the implementation here for quite some while, there are couple of problems with the approach discussed in our huddle. 

- If I create the VersionedPluginModule and then add it to PluginModule, then the other types of Plugins (DashboardPlugin, WidgetPlugins, etc.) do not have the plugin version, since they extend Plugin not PluginModule, which becomes problematic since:
ie. the property `component` does not exist on `type VersionedPluginModule,` because the `isWidgetPlugin` expects a `PluginModule`, not a `VersionedPluginModule` (which has the additional required property of `version`), and then in the `isWidgetPlugin`, we cast the type by doing `plugin is WidgetPlugin`, which then causes an **error**, since the `WidgetPlugin` does not have `version`. The solution would be manually adding `version` to each of the plugins , but then it is more efficient to just add `version` to the `base Plugin interface`. 

- I am currently trying to see if there is **any other way** where we do not have to add it to the base `Plugin`, but if not, there is not much sense in creating the `VersionedPluginModule` , since the `PluginModule` will already have it by ways of the `Plugin`
