### ISSUE TITLE
@deephaven/eslint-config shouldn't have peer dependencies

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#1386]
**Description**
@deephaven/eslint-config should not have any peer dependencies. Right now it can cause problems when including `@deephaven/eslint-config` (like we do from the `deephaven-ipywidgets` project).

**Comment by mattrunyon** [comment]
Eslint explicitly says you should have peer dependencies for eslint and plugins [here](https://eslint.org/docs/latest/extend/shareable-configs#publishing-a-shareable-config)

They are loaded relative to the end user's project, so that's why they need to be peer deps

What is the specific problem with including with the `deephaven-ipywidgets` project?
