### ISSUE TITLE
Reducers are not exported from dashboard-core-plugins and dashboard packages

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#1487]
We export all our reducers from `@deephaven/redux`: https://github.com/deephaven/web-client-ui/blob/c24d1911aa97d13ece3bebfae41b9ec75f33f580/packages/redux/src/index.ts#L5

However, in the `@deephaven/dashboard` and `@deephaven/dashboard-core-plugins` packages, we have reducers that we register with the store that we do not export from the package:
https://github.com/deephaven/web-client-ui/blob/c24d1911aa97d13ece3bebfae41b9ec75f33f580/packages/dashboard/src/redux/index.ts#L2
https://github.com/deephaven/web-client-ui/blob/c24d1911aa97d13ece3bebfae41b9ec75f33f580/packages/dashboard-core-plugins/src/redux/index.ts#L2

For integrating with other applications that may have their own store, we should export all our reducers.

**Comment by mattrunyon** [comment]
I was looking at de-coupling redux from `dashboard` today because `dashboard` also handles `DashboardPlugin` and I'd prefer to pull that out. The only reducer/actions in `dashboard` include their types from `redux` already. The only usage of `redux` in `dashboard` is to get the data in `Dashboard.tsx`. `data` is defined as a prop, but doesn't seem to be read as a prop.

I think the `dashboard` actions/reducers should be moved to the `redux` package instead of just exported. The `dashboard-core-plugins` actions/reducers could be moved or just exported.

**Comment by mofojed** [comment]
Move the actions/reducers from `dashboard` and export the ones from `dashboard-core-plugins`

**Comment by georgecwan** [comment]
The reducers in `dashboard-core-plugins` will be removed since they are unused
