### ISSUE TITLE
Notebooks are empty after Docker container restarts

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/web-client-ui#1534]
**Description**

In the last few days, I've had a few instances where I exit and restart my Docker container, only to find the notebook I was working on empty. I only saw it happen for notebooks _not_ in a folder, though I didn't test it with notebooks in folders.

**Steps to reproduce**

Create a notebook, write a simple query, save it, and reload the Docker container.

**Expected results**

The notebook to appear as I was working on it before restarting my container.

**Actual results**

The notebook development panel is empty, despite having text in it previously.

**Additional details and attachments**

**Versions**

 - Engine Version: 0.28.1
 - Web UI Version: ...
 - Java Version: ...
 - Barrage Version: ...
 - OS: OS X
 - Browser: Chrome
 - Docker: 20.10.13

**Comment by mattrunyon** [comment]
This seems to only be an issue for a notebook that was created and saved, but never closed after it was created. Current workaround would be to re-open the notebook from the file explorer and it should be good from that point forward.

Also appears you do not need to restart the server, just refresh the page in this case.

The issue is the fileMetadata doesn't get updated for the panel which makes the panel not rehydrate properly on reload.

![image](https://github.com/deephaven/web-client-ui/assets/8619789/9dbe1783-8169-4eb4-8793-db9d5d129ac5)

If there are any cases of the notebook still being empty when re-opened from the file explorer, then we'll need more specifics on how to reproduce.

**Comment by mattrunyon** [comment]
Confirmed works in DHC 0.27.0 (web UI 0.45.1), but not 0.28.0 (web UI 0.47.0). Also test DHC 0.27.0 w/ a newer web UI and the bug exists there, so seems to be a web UI issue, not core

**Comment by mattrunyon** [comment]
Broken by #1451
