### ISSUE TITLE
Rollups don't work in Core+ persistent queries

### ISSUE THREAD

**Issue by rbasralian** [deephaven/web-client-ui#1665]
Rollups in Core+ workers render in code studios, but not persistent queries:

```
keys = ['a', 'b', 'c']
t = emptyTable(1000).update("Key=keys[i%keys.size()]", "Num=ii%5", "Rnd=Math.random()")
rollup = t.rollup([AggMin("RndMin=Rnd"), AggMax("RndMax=Rnd")], "Key", "Num")
```

Code studio:

![image](https://github.com/deephaven/web-client-ui/assets/9516585/d8333a0b-faa0-4b45-b706-ab792036f665)

Persistent query — the browser logs just have `LogProxy.js:87 [IrisGridPanel] Timeout after 10000ms`, and there is nothing interesting in the worker logs:

![image](https://github.com/deephaven/web-client-ui/assets/9516585/b8277042-2a3b-48f2-bd04-5f2e26f1d9d3)

![image](https://github.com/deephaven/web-client-ui/assets/9516585/1e829571-9dc0-4cf4-a8d6-0625cfdee5b5)

(This is on `1.20230511.391`/`DHC `0.30.0`)

**Comment by mofojed** [comment]
The issue here is the variable type returned from the PQ is `TreeTable`, but when we try and fetch the object, the type it's expecting is `HierarchicalTable`, and then we never "find" the variable: https://github.com/deephaven/deephaven-core/blob/fa233eefbd57593344cc35649ef0ab525205fa4b/web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java#L706. 
I'm not sure how the `TreeTable` type is getting populated exactly. Will need to dig up why that is getting the wrong type.

**Comment by mofojed** [comment]
Filed Enterprise ticket DH-16054 to address this issue.
