### ISSUE TITLE
Clicking on a (single) selected row should not unselect it

### ISSUE THREAD

**Issue by rbasralian** [deephaven/web-client-ui#1704]
If I double-click a row in the UI, it should still be selected, rather than the first click selecting it and the second click unselecting it. (You can still unselect a row with cmd+click.) In particular, it's confusing for linked tables, since you wind triggering the links based on an unselected row.

It'd also be more consistent with the multiple-row-selection experience — if you click and drag to select a handful of rows, and then click on one of them, it updates the selection to be just the one row you clicked on (rather than unselecting that row). And if click and drag to select select a handful of rows, and then click and drag again on the same set of rows, you wind up with all of them selected instead of unselected.

(It's also how the legacy swing UI works).

**Comment by dsmmcken** [comment]
I agree on the double-click leaving the row unselected in a linker scenario sucks. I propose we address this by having double click always result in the row being selected (rather than toggling twice, with the result being the inverse of however it started).

However, I like that single click still unselects. It is a familiar pattern, and I think we should leave that as is.

ex. react-spectrum list (this component will eventually be something users can create via dh.ui, so it's good to have the same behavior).

![spectrum](https://github.com/deephaven/web-client-ui/assets/1576283/9f26b764-1414-4ef6-9ebf-03b04db15507)

ex. gmail, I acknowledge this contains a checkbox so it's not quite the same as our row based selection but, feels similar in a way users would find familiar:

![selection](https://github.com/deephaven/web-client-ui/assets/1576283/08041a98-3c42-4b53-ae08-1fb0eba21420)
