### ISSUE TITLE
Add properties to control the rendering of times and other types

### ISSUE THREAD

**Issue by chipkent** [deephaven/web-client-ui#1751]
Only some of the type rendering configuration defaults are exposed via properties.  For example, there is no property to set the default time rendering format.

**Comment by mofojed** [comment]
We actually do have the `dateTimeFormat` property in community for default time format: https://github.com/deephaven/web-client-ui/blob/e1b4562585fd6ea07efe085fe7ae5128a689ce37/packages/code-studio/src/storage/LocalWorkspaceStorage.ts#L62
The other props we have are:
- `dateTimeFormat`: default date and time format
- `timeZone`: default time zone
- `showTimeZone`: Whether to show the time zone in date cells or not
- `showTSeparator`: Whether to show the T separate in date cells or not
- `decimalFormat`: Default decimal format
- `integerFormat`: Default integer format
- `truncateNumbersWithPound`: Whether to display `###` when a number is truncated instead of the truncated number
- `isMinimapEnabled`: Whether to display the minimap in notebook editors or not

**Comment by vbabich** [comment]
There's a docs ticket logged, closing this.
