### ISSUE TITLE
Move away from Enzyme to @testing-library/react

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#440]
After updating to React v17, we should move away from Enzyme to @testing-library/react. The adapter for v17 is not official.

- [x] #562
- [x] #563
- [x] #570
- [x] #593

**Comment by dsmmcken** [comment]
Similar to the ts migration, this can be broken down and worked on in smaller chunks. It's only a few dozen test that depend on enzyme.

**Comment by spasovski** [comment]
We'll face some difficulties with this so here are some notes about how to proceed with RTL:

- pretty much all calls to enzyme's `mount()` can be replaced with RTL's `render()` which returns things like `component`, `unmount`, `getByRole` etc
- user events like the previous `simulate()` will now use `userEvent` documented in https://testing-library.com/docs/ecosystem-user-event/
- access to a component's state is simply no longer possible - these tests will instead need to test things exposed to the DOM like the presence of a CSS class or the right number of child elements of a specific type
- access to a component's internal methods will no longer be possible so it is important to trigger the right combination of user actions to test the flow of functionality as expected

The biggest and most notable single change will be the lack of enzyme's `shallow`. RTL's docs suggest Jest's mocking for this https://testing-library.com/docs/react-testing-library/migrate-from-enzyme/#how-to-shallow-render-a-component but it doesn't look like a trivial undertaking. Perhaps if all leaf node components are well tested it shouldn't be necessary to test higher level parent components.

RTL brings with it a new philosophy of testing a component's usage intent rather than internal implementation. This should lead to more resilient tests (you may move something out of state for example, yet still retain existing functionality).

As a last note RTL does not replace Jest itself. Access to `expect()`, `test()` etc will still remain and be used in the same way. I've noticed some things are easier to access in RTL due to `component` from `render()` - this gives you JS access to the DOM and you can than use things like `querySelector()`, `classList` etc.

**Comment by SparkyFnay** [comment]
Should we close this ticket now that all the components are completed?

**Comment by mofojed** [comment]
All components are completed, this can be closed.
