### ISSUE TITLE
Column resize snap causing errors

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/web-client-ui#476]
**Description**

If you click and hold the column resize handle for a second and then move, it does not work. Also, if you try to resize a column through a snap point, it stops at the snap point w/ the same error. You currently have to resize to the snap point, release, then resize smaller/larger if you want to go past the snap point. This is also true of the hide snap point.

**Steps to reproduce**
Create a table
```python
from deephaven.TableTools import newTable, stringCol, charCol, intCol
from deephaven.conversion_utils import  NULL_INT;

source = newTable(
    stringCol("Value", "A" , "B", "C", "D", "E", "", None),
    charCol("Char", "A", "B", "C", "D", "E", " ", None),
    intCol("Int", 1, 2, 3, 4, 5, 6, NULL_INT)
)
```

1. Click and hold on the column resize handle for a second and then try to resize the column without releasing the mouse button.

2. Try to resize from a column larger than its original size to a size smaller than original.

**Expected results**

Resize

**Actual results**

1. No resize. Repeated errors in log
2. Resize stops at snap point. Repeated errors in log

```
Uncaught Error: Missing value for key 0
    at getOrThrow (:4000/static/js/main.chunk.js:77356:9)
    at GridColumnSeparatorMouseHandler.onDrag (:4000/static/js/main.chunk.js:89085:103)
    at Grid.notifyMouseHandlers (:4000/static/js/main.chunk.js:76648:76)
    at Grid.handleMouseDrag (:4000/static/js/main.chunk.js:76719:10)
```

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: 0.11.0
 - Browser: Chrome

**Comment by mofojed** [comment]
@mattrunyon are there any extra steps for triggering this? I can't seem to reproduce on latest main in Chrome

**Comment by mattrunyon** [comment]
Might be related to tables that are reopened when the tab is reloaded and "disconnect on close" is not enabled

**Comment by mofojed** [comment]
Still can't seem to reproduce...

**Comment by dsmmcken** [comment]
I can reproduce.

1. Run a query that produces a table, example:

```
from deephaven.TableTools import emptyTable
t = emptyTable(100).update("x = i", "y = i", "z = i")
```

2. Resize the first column to be wider.
3. Refresh the browser, and wait for that table to re-load
4. Attempt to resize that same first column.

Expected: column resizes
Result: Error

Happens everytime for me in chrome on latests build.

**Comment by dsmmcken** [comment]
> Yup that doesn't work ~~works~~, thanks!

**Comment by mofojed** [comment]
Narrowed down the issue... so the problem is that in the [GridSeparatorMouseHandler](https://github.com/deephaven/web-client-ui/blob/7aa0f112e0ee2ebe7dbf28735d29a7bf7c0b9be0/packages/grid/src/mouse-handlers/GridSeparatorMouseHandler.ts#L165), we're trying to get the columns calculated size from the calculatedColumnWidths map, but because there's already a user defined column width set, we don't calculate it in either [IrisGridMetricCalculator](https://github.com/deephaven/web-client-ui/blob/7aa0f112e0ee2ebe7dbf28735d29a7bf7c0b9be0/packages/iris-grid/src/IrisGridMetricCalculator.ts#L39) or [GridMetricCalculator](https://github.com/deephaven/web-client-ui/blob/7aa0f112e0ee2ebe7dbf28735d29a7bf7c0b9be0/packages/grid/src/GridMetricCalculator.ts#L1426).

We should probably always make sure that calculated map is up to date.
