### ISSUE TITLE
Plot.ly 2.0 upgrade

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#49]
Review for breaking changes, and bump dependency.

**Comment by mofojed** [comment]
This is going to be a bit of a pain to test, because plotting doesn't actually work on OSS right now (@niloc132 's changes haven't merged).

Will need to wait for my package updates to merge into bard, and then use `npm link` to test it out.

**Comment by dsmmcken** [comment]
For dev testing, could just bump the version in enterprise locally, check it and then if everything is fine bump it here. Hard for QA to test until it merges all the way through.

My reading of the release notes make me think we will notice zero difference in this version bump.

**Comment by mofojed** [comment]
Yea that's another option, checking it on bard before I merge all the packages to use OSS side.
For the @deephaven/chart package, I added plotly as a dep instead of a peer dependency, so consumer is abstracted from the actual plotting library used. Then we could switch out plotly before Apache ECharts or uPlot or something without the consumer worrying about it.
