### ISSUE TITLE
Wrong row numbers for InputTable in the WebUI

### ISSUE THREAD

**Issue by jmao-denver** [deephaven/web-client-ui#889]
<img width="1897" alt="image" src="https://user-images.githubusercontent.com/4297243/201998500-4a895c76-ebfe-48bf-923d-ede09885d165.png">

This was discovered during the debugging of a problem with the new InputTable Python wrapper.
I have already talked to @niloc132 about it and experimented a bit more, the preliminary diagnosis is that UI might confuses with the reserved rows for editing and the actual table size.

**Comment by mofojed** [comment]
The problem is in `IrisGridModel` we override the `rowCount` to specify the number of 'extra' rows to draw in the grid, while also using the same number in the table tooltip.
We probably shouldn't override the `rowCount`, and instead have a mechanism to specify drawing additional rows in the grid... or the tooltip should pull from a "Number of rows" API (exclude the 'extra' rows).
